# Generated by Django 4.1.2 on 2022-10-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='experience',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
